/** Generated by tools/build-default-font-catalog.py. Do not edit by hand. */
(function(global) {
  "use strict";
  global.ESPIDE_DEFAULT_FONTS = Object.freeze([
  {
    "id": "font-3x6",
    "name": "Font 3×6",
    "fileName": "font_3x6.mfnt",
    "width": 3,
    "height": 6,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_3x6.mfnt",
    "preview": "js/display_designer/default_fonts/font_3x6.png"
  },
  {
    "id": "font-5x8",
    "name": "Font 5×8",
    "fileName": "font_5x8.mfnt",
    "width": 5,
    "height": 8,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_5x8.mfnt",
    "preview": "js/display_designer/default_fonts/font_5x8.png"
  },
  {
    "id": "font-6x14-bold",
    "name": "Font 6×14 Bold",
    "fileName": "font_6x14_bold.mfnt",
    "width": 6,
    "height": 14,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_6x14_bold.mfnt",
    "preview": "js/display_designer/default_fonts/font_6x14_bold.png"
  },
  {
    "id": "font-12x24",
    "name": "Font 12×24",
    "fileName": "font_12x24.mfnt",
    "width": 12,
    "height": 24,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_12x24.mfnt",
    "preview": "js/display_designer/default_fonts/font_12x24.png"
  },
  {
    "id": "font-16x28",
    "name": "Font 16×28",
    "fileName": "font_16x28.mfnt",
    "width": 16,
    "height": 28,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_16x28.mfnt",
    "preview": "js/display_designer/default_fonts/font_16x28.png"
  },
  {
    "id": "font-7x16",
    "name": "Font 7×16",
    "fileName": "font_7x16.mfnt",
    "width": 7,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/font_7x16.mfnt",
    "preview": "js/display_designer/default_fonts/font_7x16.png"
  },
  {
    "id": "spleen-8",
    "name": "Spleen",
    "fileName": "spleen_8.mfnt",
    "width": 5,
    "height": 8,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_8.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_8.png"
  },
  {
    "id": "spleen-12",
    "name": "Spleen",
    "fileName": "spleen_12.mfnt",
    "width": 6,
    "height": 12,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_12.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_12.png"
  },
  {
    "id": "spleen-16",
    "name": "Spleen",
    "fileName": "spleen_16.mfnt",
    "width": 8,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_16.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_16.png"
  },
  {
    "id": "spleen-24",
    "name": "Spleen",
    "fileName": "spleen_24.mfnt",
    "width": 12,
    "height": 24,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_24.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_24.png"
  },
  {
    "id": "spleen-32",
    "name": "Spleen",
    "fileName": "spleen_32.mfnt",
    "width": 16,
    "height": 32,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_32.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_32.png"
  },
  {
    "id": "spleen-64",
    "name": "Spleen",
    "fileName": "spleen_64.mfnt",
    "width": 32,
    "height": 64,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/spleen_64.mfnt",
    "preview": "js/display_designer/default_fonts/spleen_64.png"
  },
  {
    "id": "ter-14-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_14_narrow.mfnt",
    "width": 8,
    "height": 14,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_14_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_14_narrow.png"
  },
  {
    "id": "ter-16-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_16_narrow.mfnt",
    "width": 8,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_16_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_16_narrow.png"
  },
  {
    "id": "ter-20-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_20_narrow.mfnt",
    "width": 10,
    "height": 20,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_20_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_20_narrow.png"
  },
  {
    "id": "ter-22-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_22_narrow.mfnt",
    "width": 11,
    "height": 22,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_22_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_22_narrow.png"
  },
  {
    "id": "ter-24-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_24_narrow.mfnt",
    "width": 12,
    "height": 24,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_24_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_24_narrow.png"
  },
  {
    "id": "ter-28-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_28_narrow.mfnt",
    "width": 14,
    "height": 28,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_28_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_28_narrow.png"
  },
  {
    "id": "ter-32-narrow",
    "name": "Terminus Narrow",
    "fileName": "ter_32_narrow.mfnt",
    "width": 16,
    "height": 32,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_32_narrow.mfnt",
    "preview": "js/display_designer/default_fonts/ter_32_narrow.png"
  },
  {
    "id": "ter-12-bold",
    "name": "Terminus Bold",
    "fileName": "ter_12_bold.mfnt",
    "width": 6,
    "height": 12,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_12_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_12_bold.png"
  },
  {
    "id": "ter-14-bold",
    "name": "Terminus Bold",
    "fileName": "ter_14_bold.mfnt",
    "width": 8,
    "height": 14,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_14_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_14_bold.png"
  },
  {
    "id": "ter-16-bold",
    "name": "Terminus Bold",
    "fileName": "ter_16_bold.mfnt",
    "width": 8,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_16_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_16_bold.png"
  },
  {
    "id": "ter-20-bold",
    "name": "Terminus Bold",
    "fileName": "ter_20_bold.mfnt",
    "width": 10,
    "height": 20,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_20_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_20_bold.png"
  },
  {
    "id": "ter-22-bold",
    "name": "Terminus Bold",
    "fileName": "ter_22_bold.mfnt",
    "width": 11,
    "height": 22,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_22_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_22_bold.png"
  },
  {
    "id": "ter-24-bold",
    "name": "Terminus Bold",
    "fileName": "ter_24_bold.mfnt",
    "width": 12,
    "height": 24,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_24_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_24_bold.png"
  },
  {
    "id": "ter-32-bold",
    "name": "Terminus Bold",
    "fileName": "ter_32_bold.mfnt",
    "width": 16,
    "height": 32,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/ter_32_bold.mfnt",
    "preview": "js/display_designer/default_fonts/ter_32_bold.png"
  },
  {
    "id": "tamzen-8",
    "name": "Tamzen",
    "fileName": "Tamzen_8.mfnt",
    "width": 5,
    "height": 8,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_8.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_8.png"
  },
  {
    "id": "tamzen-13",
    "name": "Tamzen",
    "fileName": "Tamzen_13.mfnt",
    "width": 7,
    "height": 13,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_13.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_13.png"
  },
  {
    "id": "tamzen-16",
    "name": "Tamzen",
    "fileName": "Tamzen_16.mfnt",
    "width": 8,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_16.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_16.png"
  },
  {
    "id": "tamzen-8-bold",
    "name": "Tamzen Bold",
    "fileName": "Tamzen_8_bold.mfnt",
    "width": 5,
    "height": 8,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_8_bold.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_8_bold.png"
  },
  {
    "id": "tamzen-13-bold",
    "name": "Tamzen Bold",
    "fileName": "Tamzen_13_bold.mfnt",
    "width": 7,
    "height": 13,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_13_bold.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_13_bold.png"
  },
  {
    "id": "tamzen-16-bold",
    "name": "Tamzen Bold",
    "fileName": "Tamzen_16_bold.mfnt",
    "width": 8,
    "height": 16,
    "category": "text",
    "sample": "ABCabc123",
    "path": "js/display_designer/default_fonts/Tamzen_16_bold.mfnt",
    "preview": "js/display_designer/default_fonts/Tamzen_16_bold.png"
  },
  {
    "id": "7-seg-33x19",
    "name": "7 Segment",
    "fileName": "7_Seg_33x19.mfnt",
    "width": 18,
    "height": 32,
    "category": "numeric",
    "sample": "0123.456789",
    "path": "js/display_designer/default_fonts/7_Seg_33x19.mfnt",
    "preview": "js/display_designer/default_fonts/7_Seg_33x19.png"
  }
]);
})(window);
