name: Build and Release ESP IDE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      #––– Linux-only závislosti pro .deb / AppImage ––––––––––––––––––––––––––
      - name: Install build deps (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y fakeroot dpkg rpm  # .deb vyžaduje fakeroot+dpkg :contentReference[oaicite:0]{index=0}

      #––– Zapnutí globálního no-sandbox pro buildované binárky –––––––––––––––
      - name: Set no-sandbox env (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: echo "ELECTRON_DISABLE_SANDBOX=1" >> $GITHUB_ENV   # stejné jako --no-sandbox :contentReference[oaicite:1]{index=1}

      - name: Install JS dependencies
        run: npm ci

      - name: Build app
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            npm run dist:linux          # generuje AppImage + .deb (viz build.linux v package.json) :contentReference[oaicite:2]{index=2}
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            npm run dist:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npm run dist:mac
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ESP_IDE_${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/**/*Setup*.exe
            ./artifacts/**/*.dmg
            ./artifacts/**/*.AppImage
            ./artifacts/**/*.deb        # ← nově přidáno
            ./artifacts/**/*-mac.zip
